### ISSUE TITLE
Wishlist: can be as easily used as Getopt::Std

### ISSUE THREAD

**Issue by perlancar** [perlancar/perl-Getopt-Long-More#23]
I'm not sure if this is strictly "more stuff", so for now I'll put it under wishlist: things that would be nice to have.

It would be nice if GLM can be used as easy as Getopt::Std (GoS) if not easier; for testing in one-liners, for example. For example, using import argument:

    % perl -MGetopt::Long::More=:oif: -e '...'     ;# : prefix, will conflict with GoL's :config
    % perl -MGetopt::Long::More=oif: -e '...'      ;# no prefix, simpler, any unknown import arg 
                                                 # assumed to be option spec

-o, -i are boolean flags, -f takes an argument.

This can be extended to long options, e.g.:

    % perl -MGetopt::Long::More=:foo,bar=s,baz -e '...'
    % perl -MGetopt::Long::More=foo,bar=s,baz -e '...'

--foo and --baz are flags, --bar takes argument.

The default destination will be used (setting caller's $opt_XXX or whatever).

**Comment by tabulon** [comment]
That wouln't be bad thing, imho; but I would vouch for a distinct prefix to prevent things getting hairy along the way. Since `:` is taken , why not pick something else (e.g. `=`)?

Also, the benefit could perhaps become more apparent if `Getopt::Long::More` could be mirrored at another -shorter- namespace, such as `GLM` (literally)... in which case the above would become:

```bash
% perl -MGLM==foo,bar=s,baz -e '...'
```
That being said, for these one-liner cases, I usually reach out for the seldom used poor-man's option processing provided natively by the perl executable itself  (with the `-s` switch ), like so:

 ```bash
# note the '-s', the double-dash (--) and also the old style option: '-foo'
% perl -se 'print "Hello, ${foo}!"' -- -foo=World   
```

**Comment by perlancar** [comment]
Rereading this again after some time passes, now I don't think this is quite in line with the raison d'être of GLM as the drop-in replacement for GoL. Nor GoL neither Getopt::Std itself support this.syntax. It would be best served with some other module (the abovementioned GLM or GS or 'stdopt' or whatever:

    % perl -Mstdopt=:oif: -e ...

Thanks for reminding me about perl's `-s`. I don't think I've ever used that once in my life :)

**Comment by tabulon** [comment]
:-)
